name: steve_server_cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - websockets
  - tqdm
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip:
    - gymnasium==0.29.1
    - stable-baselines3==2.3.2
